version: '3.8'

services:
  app:
    build: .
    container_name: gold_price_alert_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
  
  db:
    image: mysql:8.0
    container_name: gold_price_alert_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel # Replace with your desired database name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: gold_price_alert_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"  # Change Jenkins port to avoid conflicts
    user: root
    environment:
      - JENKINS_UC_DOWNLOAD=https://updates.jenkins.io
    volumes:
      - jenkins_home:/var/jenkins_home


networks:
  laravel_network:

volumes:
  dbdata:
  jenkins_home:
