global:
  scrape_interval: 15s  # Collect metrics every 15 seconds

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # Monitor Prometheus itself

  - job_name: "node"
    static_configs:
      - targets: ["docker.for.mac.localhost:9100"]  # Use this on Mac

  - job_name: 'laravel-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']