apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: my-laravel-app  # Using local image
          imagePullPolicy: Never  # <--- Add this to use local image
          ports:
            - containerPort: 80

