name: Deploy to Nuc Server

on:
  push:
    branches:
      - k8s-test  # Change this if your main branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server via SSH Password
        run: |
          sshpass -p "${{ secrets.NUC_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.NUC_IP_ADDRESS }} << 'EOF'
            echo 'TESTING'
            # cd /var/www/Malaysia-Gold-Price-Alert
            # git pull origin k8s-test  # Pull the latest code
            # docker-compose down   # Stop existing containers
            # docker-compose build  # Build the new Docker image
            # docker-compose up -d  # Start the updated containers
          EOF
