name: Deploy to Nuc Server

on:
  push:
    branches:
      - k8s-test  # Change this if your main branch is named differently

env:
  USERNAME: dvy
  PORT : 22

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.NUC_IP_ADDRESS }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.NUC_PASSWORD }}
          port: ${{ env.PORT }}
          command_timeout: 30m
          script: |
            echo 'Successfully connected to server'

      - name: Echo message
        run: |
          echo "Successfully connected to server"
